### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by joehoyle**
Currently many things are broken in Windows, due to not testing paths, env vars, ttys and more. This fixes up all the errors I ran into, until I get a functioning Windows setup!

This was opened in the GH web UI, from 3.* so this diff needs cleaning still (e.g. ` 				$output->writeln( sprintf( '<error>WordPress install failed. Exited with error code %d</>', $install_failed ) );` should not have been deleted.

### CODE REVIEW

**Comment by joehoyle** [comment]
Also, we need to add support for testing of `$_ENV` is empty. On windows, the `php.ini` defaults to GPCS (per https://www.php.net/manual/en/ini.core.php#ini.variables-order) so we should add a check for that.

**Comment by roborourke** [comment]
Nice! Can that ini setting be changed at run time with `ini_set()` or setting `auto_globals_jit`?

Code looks good apart from the linter errors.

**Comment by joehoyle** [comment]
I think no, as ENV is populated on the process bootstrap

-- 

Joe Hoyle

CTO
Human Made

**Comment by rmccue** [comment]
@joehoyle Given we have WSL2 support, is there anything else in this PR that might be worth retaining?

**Comment by roborourke** [comment]
🔥

**Comment by joehoyle** [comment]
Yeah can be deleted!

**Pull request closed without merging**
