### PR TITLE
Set TTY depending on execution context for all processes

### PR DESCRIPTION
**Pull request by roborourke**
Makes sure that output is properly formatted.

### CODE REVIEW

**Comment by roborourke** [comment]
Here's the follow on @tfrommen!

**Comment by rmccue** [comment]
These should be set based on whether the current process is a TTY, no?

**Comment by roborourke** [comment]
The start command has had this for ages so we're bringing them in line with that https://github.com/humanmade/altis-local-server/pull/328

We only use tty detection for the `exec` command right now.

**Comment by rmccue** [comment]
Seems like they should consistently do so though; otherwise, something like `composer server logs php | tee some.log | tail -f` will likely break.

**Comment by roborourke** [comment]
Using `$process->setPty( true )` ([pseudo terminal](https://symfony.com/doc/current/components/process.html#using-tty-and-pty-modes)) works, Symfony figures out whether the output is being piped to something else or not.

**Review by tfrommen — APPROVED** [review]
**_Colors!_** 😍

**Comment by rmccue** [comment]
I am thinking more like `$process->setTty( posix_isatty( STDOUT ) )`; passing the code through. Setting pty won't pass through interactive prompts if those would have occurred (iirc)

**Pull request merged**
