### PR TITLE
Turn on error display for local server

### PR DESCRIPTION
**Pull request by pdewouters**
Screenshot 2020-07-06 at 11 13 45

### CODE REVIEW

**Comment by pdewouters** [comment]
@joehoyle are the acceptance criteria here outdated then? https://github.com/humanmade/altis-local-server/issues/123

**Comment by joehoyle** [comment]
Ah thanks for linking @pdewouters -- could you link the original issues in subsequent PRs too to give extra context.

It looks like that acceptance criteria actually came from @roborourke! He edited my comment :D 

It does actually looked like we want to rmove display_errors from the web context per @rmccue 's response: 

> FWIW, it's already turned on in the local-server bootstrap file, but we should actually remove this so that errors aren't displayed in a HTML context:

I guess that's fine, though I'm not entirely sure why we don't want to show errors in the web context! In which case anyway, judging by the notes on #123 then this PR is good to go.

**Comment by rmccue** [comment]
I think this should be set in the .ini rather than in wp-config FWIW

**Comment by joehoyle** [comment]
@rmccue that will affect both web and cli though, which you comment specifically recommends against I think?

**Comment by rmccue** [comment]
Yeah; I think local-server might need to distinguish the two SAPIs and separate the configuration, the same way that e.g. Ubuntu PHP does.

**Pull request merged**
